import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster"; // Modified import statements
import Navbar from "@/components/navbar/Navbar"; // Modified import statements
import ApiContextProvider from "@/context/apiContext";
import ImageContextProvider from "@/context/ImageContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ImageContextProvider>
            <ApiContextProvider>
              <Navbar/>
              {children}
              <Toaster/>
            </ApiContextProvider>
          </ImageContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
